import React from "react";
import { getReportTranslation, getScriptFontFamily } from "@/utils/reportTranslations";

interface ExecutiveReportPrintViewProps {
  caseData: any;
  execSummaryData: any;
  graphData: any;
  timelineData: any;
  permissions: string[];
  activities: string[];
  services: string[];
  mitreTags: { id: string; name: string }[];
  iocs: { type: string; value: string; severity: string }[];
  threatNarrative: any;
  citizenImpact: any;
  langCode?: string;
  regionalAdvisory?: any;
}

// ─── Design tokens ────────────────────────────────────────────────────────────
const ACCENT    = "#0f172a";   // near-black headings
const RED       = "#b91c1c";   // critical
const ORANGE    = "#c2410c";   // high
const AMBER     = "#92400e";   // medium
const GREEN     = "#166534";   // low/safe
const BRAND     = "#0e7490";   // BeaconTrap cyan (print-safe)
const BRAND_BG  = "#ecfeff";
const STRIPE    = "#f8fafc";   // table alternating row
const BORDER    = "#cbd5e1";
const MONO_FONT = "'JetBrains Mono', 'Courier New', monospace";
const TOTAL_PAGES = 15;

// ─── Helpers ──────────────────────────────────────────────────────────────────
function fmt(date: any) {
  if (!date) return "N/A";
  const d = new Date(date);
  return isNaN(d.getTime()) ? "N/A" : d.toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" });
}

function riskMeta(score: number) {
  if (score >= 80) return { label: "CRITICAL", color: RED,    bg: "#fef2f2", border: "#fca5a5" };
  if (score >= 60) return { label: "HIGH",     color: ORANGE, bg: "#fff7ed", border: "#fdba74" };
  if (score >= 40) return { label: "MEDIUM",   color: AMBER,  bg: "#fffbeb", border: "#fcd34d" };
  return             { label: "LOW",      color: GREEN,  bg: "#f0fdf4", border: "#86efac" };
}

// ─── Shared sub-components ────────────────────────────────────────────────────
function PageHeader({ pageNum, section, pageFont }: { pageNum: number; section: string; pageFont: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center",
      borderBottom: `3px solid ${ACCENT}`, paddingBottom: 8, marginBottom: 24,
      fontFamily: pageFont, lineHeight: 1.5 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
        <span style={{ background: ACCENT, color: "#fff", padding: "2px 10px",
          fontSize: 9, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase" }}>
          BeaconTrap Intelligence
        </span>
        <span style={{ fontSize: 9, fontWeight: 700, color: BRAND, letterSpacing: 1.5, textTransform: "uppercase" }}>
          {section}
        </span>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
        <span style={{ fontSize: 9, color: "#64748b", fontFamily: MONO_FONT }}>
          Page {pageNum} of {TOTAL_PAGES}
        </span>
        <span style={{ background: RED, color: "#fff", padding: "2px 8px",
          fontSize: 9, fontWeight: 700, letterSpacing: 2 }}>
          CONFIDENTIAL
        </span>
      </div>
    </div>
  );
}

function PageFooter({ caseId, pageFont }: { caseId: string; pageFont: string }) {
  return (
    <div style={{ marginTop: "auto", paddingTop: 14, borderTop: `1px solid ${BORDER}`,
      display: "flex", justifyContent: "space-between", alignItems: "center",
      fontFamily: pageFont, fontSize: 8, color: "#94a3b8", lineHeight: 1.5 }}>
      <span>Generated by BeaconTrap AI Intelligence Platform · Case: <code style={{ fontFamily: MONO_FONT }}>{caseId}</code></span>
      <span>© BeaconTrap · For Authorized Personnel Only</span>
    </div>
  );
}

function SectionTitle({ num, title, pageFont }: { num: string; title: string; pageFont: string }) {
  return (
    <div style={{ marginBottom: 18, fontFamily: pageFont }}>
      <div style={{ fontSize: 10, fontWeight: 700, color: BRAND, letterSpacing: 2,
        textTransform: "uppercase", marginBottom: 4 }}>
        Section {num}
      </div>
      <h2 style={{ fontSize: 20, fontWeight: 800, color: ACCENT, margin: 0,
        fontFamily: pageFont, letterSpacing: 0.5, lineHeight: 1.4,
        borderLeft: `5px solid ${BRAND}`, paddingLeft: 14 }}>
        {title}
      </h2>
    </div>
  );
}

function CalloutBox({ title, children, color = BRAND, pageFont }: { title: string; children: React.ReactNode; color?: string; pageFont: string }) {
  return (
    <div style={{ background: BRAND_BG, border: `1px solid ${BORDER}`,
      borderLeft: `5px solid ${color}`, padding: "14px 18px", marginBottom: 16,
      fontFamily: pageFont, lineHeight: 1.6 }}>
      <div style={{ fontSize: 9, fontWeight: 800, color, textTransform: "uppercase",
        letterSpacing: 1.5, marginBottom: 6 }}>{title}</div>
      <div style={{ fontSize: 11, color: "#1e293b", lineHeight: 1.6 }}>{children}</div>
    </div>
  );
}

function SeverityBadge({ label, pageFont }: { label: string; pageFont: string }) {
  const rm = riskMeta(label === "CRITICAL" ? 90 : label === "HIGH" ? 70 : label === "MEDIUM" ? 50 : 20);
  return (
    <span style={{ display: "inline-block", background: rm.bg, color: rm.color,
      border: `1px solid ${rm.border}`, padding: "2px 10px", fontWeight: 800,
      fontSize: 9, letterSpacing: 1.5, textTransform: "uppercase",
      fontFamily: pageFont }}>
      {label}
    </span>
  );
}

function Table({ headers, rows, pageFont, pageBreakInside = "avoid" }: {
  headers: string[];
  rows: (string | React.ReactNode)[][];
  pageFont: string;
  pageBreakInside?: string;
}) {
  return (
    <table style={{ width: "100%", borderCollapse: "collapse", fontFamily: pageFont,
      fontSize: 10, marginBottom: 20, lineHeight: 1.5, pageBreakInside: pageBreakInside as any }}>
      <thead>
        <tr style={{ background: ACCENT }}>
          {headers.map((h, i) => (
            <th key={i} style={{ padding: "8px 12px", textAlign: "left", color: "#fff",
              fontSize: 9, fontWeight: 700, letterSpacing: 1,
              textTransform: "uppercase", borderRight: "1px solid #334155" }}>
              {h}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, ri) => (
          <tr key={ri} style={{ background: ri % 2 === 0 ? "#fff" : STRIPE }}>
            {row.map((cell, ci) => (
              <td key={ci} style={{ padding: "7px 12px", borderBottom: `1px solid ${BORDER}`,
                borderRight: `1px solid ${BORDER}`, verticalAlign: "top" }}>
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function ScoreBar({ value, max = 100, color = BRAND }: { value: number; max?: number; color?: string }) {
  const pct = Math.min(100, (value / max) * 100);
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
      <div style={{ flex: 1, height: 8, background: "#e2e8f0", borderRadius: 4, overflow: "hidden" }}>
        <div style={{ width: `${pct}%`, height: "100%", background: color, borderRadius: 4 }} />
      </div>
      <span style={{ fontSize: 9, fontWeight: 700, color, width: 32, textAlign: "right", fontFamily: MONO_FONT }}>{value}</span>
    </div>
  );
}

// ─── Page wrapper ─────────────────────────────────────────────────────────────
function Page({ children, pageFont, pageBreakAfter = true }: { children: React.ReactNode; pageFont: string; pageBreakAfter?: boolean }) {
  return (
    <div
      className={`print-page${pageBreakAfter ? "" : " print-page-last"}`}
      style={{
        pageBreakAfter: pageBreakAfter ? "always" : "auto",
        breakAfter: pageBreakAfter ? "page" : "auto",
        padding: "36px 48px",
        display: "flex",
        flexDirection: "column",
        background: "#fff",
        fontFamily: pageFont,
        lineHeight: 1.6,
        position: "relative",
        boxSizing: "border-box",
      }}
    >
      {children}
    </div>
  );
}

// ─── Main export ──────────────────────────────────────────────────────────────
export default function ExecutiveReportPrintView({
  caseData, execSummaryData, graphData, timelineData,
  permissions, activities, services, mitreTags, iocs,
  threatNarrative, citizenImpact,
  langCode = "en", regionalAdvisory,
}: ExecutiveReportPrintViewProps) {

  const pageFont = getScriptFontFamily(langCode);
  const tr = (key: string) => getReportTranslation(key, langCode);

  const rm   = riskMeta(caseData.riskScore);
  const cid  = caseData.id;
  const date = fmt(caseData.createdAt);

  // Derived
  const criticalIocs    = iocs.filter(i => i.severity?.toLowerCase() === "critical");
  const highIocs        = iocs.filter(i => i.severity?.toLowerCase() === "high");
  const ipIocs          = iocs.filter(i => i.type?.toLowerCase() === "ip" || i.type === "IP");
  const domainIocs      = iocs.filter(i => i.type?.toLowerCase() === "domain" || i.type === "Domain");
  const highRiskPerms   = permissions.filter(p =>
    ["RECEIVE_SMS","READ_SMS","SEND_SMS","SYSTEM_ALERT_WINDOW","BIND_ACCESSIBILITY_SERVICE",
     "PROCESS_OUTGOING_CALLS","RECORD_AUDIO","CAMERA","READ_CONTACTS","ACCESS_FINE_LOCATION"]
    .some(d => p.toUpperCase().includes(d))
  );

  const scoreBreakdown = [
    { name: "Permission Risk Weight",       score: caseData.permissionScore, max: 40, color: RED    },
    { name: "IOC Footprint Score",           score: caseData.iocScore,        max: 20, color: ORANGE },
    { name: "Keyword Mimicry Score",         score: caseData.keywordScore,    max: 20, color: AMBER  },
    { name: "AI Heuristic Classifier",      score: caseData.aiConfidence,    max: 20, color: BRAND  },
  ];

  return (
    <div
      className="print-report-root hidden print:block"
      style={{ background: "#fff", fontFamily: pageFont, lineHeight: 1.6 }}
      aria-hidden="true"
    >

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 1: COVER                                                          */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        {/* Top bar */}
        <div style={{ background: ACCENT, height: 8, margin: "-36px -48px 0", width: "calc(100% + 96px)" }} />
        <div style={{ background: BRAND, height: 3, margin: "0 -48px 0", width: "calc(100% + 96px)", marginBottom: 60 }} />

        {/* Watermark-style background text */}
        <div style={{ position: "absolute", top: "38%", left: "50%", transform: "translate(-50%,-50%) rotate(-30deg)",
          fontSize: 96, fontWeight: 900, color: "rgba(15,23,42,0.03)", letterSpacing: 8,
          whiteSpace: "nowrap", userSelect: "none", pointerEvents: "none" }}>
          {tr("confidential")}
        </div>

        {/* Logo block */}
        <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 48 }}>
          <svg width="56" height="56" viewBox="0 0 24 24" fill="none" stroke={BRAND} strokeWidth="1.5">
            <path d="M12 2L3 7v5c0 5 3.5 9.74 9 11 5.5-1.26 9-6 9-11V7L12 2z" />
            <path d="M9 12l2 2 4-4" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <div>
            <div style={{ fontSize: 36, fontWeight: 900, color: ACCENT, letterSpacing: -1 }}>BeaconTrap</div>
            <div style={{ fontSize: 11, fontWeight: 600, color: BRAND, letterSpacing: 3, textTransform: "uppercase" }}>
              Cyber Threat Intelligence Platform
            </div>
          </div>
        </div>

        {/* Report title translated */}
        <div style={{ borderTop: `3px solid ${ACCENT}`, borderBottom: `1px solid ${BORDER}`,
          padding: "24px 0", marginBottom: 48 }}>
          <div style={{ fontSize: 9, fontWeight: 700, color: BRAND, letterSpacing: 3,
            textTransform: "uppercase", marginBottom: 8 }}>
            {tr("dossier_header")}
          </div>
          <h1 style={{ fontSize: 26, fontWeight: 900, color: ACCENT, margin: 0, lineHeight: 1.3 }}>
            {tr("dossier_title")}
          </h1>
          <div style={{ fontSize: 12, color: "#64748b", marginTop: 12, fontStyle: "italic" }}>
            {tr("sub_title")}
          </div>
        </div>

        {/* Case metadata grid with technical fields in Mono */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 48 }}>
          {[
            { label: tr("case_ref"), value: cid, mono: true },
            { label: tr("analysis_date"), value: date },
            { label: tr("target_binary"), value: caseData.fileName, mono: true },
            { label: tr("package_name"), value: caseData.packageName || "N/A", mono: true },
            { label: tr("sha256_hash"), value: caseData.sha256, mono: true, span: true },
          ].map((f, i) => (
            <div key={i} style={{ gridColumn: (f as any).span ? "1 / -1" : undefined,
              padding: "12px 16px", background: STRIPE, border: `1px solid ${BORDER}` }}>
              <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", letterSpacing: 1.5,
                textTransform: "uppercase", marginBottom: 4 }}>{f.label}</div>
              <div style={{ fontSize: f.mono ? 10 : 12, fontFamily: f.mono ? MONO_FONT : pageFont,
                fontWeight: 600, color: ACCENT, wordBreak: "break-all" }}>{f.value}</div>
            </div>
          ))}
        </div>

        {/* Risk score callout */}
        <div style={{ background: rm.bg, border: `2px solid ${rm.border}`, padding: "20px 24px",
          display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 48 }}>
          <div>
            <div style={{ fontSize: 9, fontWeight: 700, color: rm.color, letterSpacing: 2,
              textTransform: "uppercase", marginBottom: 4 }}>{tr("composite_risk_score")}</div>
            <div style={{ fontSize: 48, fontWeight: 900, color: rm.color, lineHeight: 1, fontFamily: MONO_FONT }}>
              {caseData.riskScore}
              <span style={{ fontSize: 16, fontWeight: 400, color: "#94a3b8" }}> / 100</span>
            </div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 24, fontWeight: 900, color: rm.color, letterSpacing: 2 }}>{rm.label}</div>
            <div style={{ fontSize: 13, color: "#64748b", marginTop: 4, fontFamily: MONO_FONT }}>
              {caseData.threatFamily || "Unclassified"}
            </div>
            <div style={{ fontSize: 11, color: "#94a3b8", fontFamily: MONO_FONT }}>
              Confidence: {caseData.aiConfidence || caseData.threatConfidence || 90}%
            </div>
          </div>
        </div>

        {/* Classification footer */}
        <div style={{ marginTop: "auto", borderTop: `3px double ${ACCENT}`, paddingTop: 16,
          display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ fontSize: 9, color: "#64748b" }}>
            Distribution: Authorized Cybersecurity Personnel Only
          </div>
          <div style={{ background: RED, color: "#fff", padding: "6px 20px",
            fontSize: 11, fontWeight: 900, letterSpacing: 2 }}>
            {tr("confidential")}
          </div>
        </div>
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 2: EXECUTIVE SUMMARY                                              */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={2} section={tr("executive_summary")} pageFont={pageFont} />
        <SectionTitle num="1" title={tr("executive_summary")} pageFont={pageFont} />

        {execSummaryData ? (<>
          <CalloutBox title={tr("strategic_risk_assessment")} color={rm.color} pageFont={pageFont}>
            {execSummaryData.executiveRiskSummary}
          </CalloutBox>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, marginBottom: 20 }}>
            {[
              { label: tr("priority_level"), value: execSummaryData.priorityLevel, color: rm.color },
              { label: tr("estimated_exposure"), value: execSummaryData.estimatedExposure, color: ORANGE },
              { label: tr("ai_confidence"), value: `${caseData.aiConfidence || 90}%`, color: BRAND },
            ].map((kpi, i) => (
              <div key={i} style={{ padding: "16px", background: STRIPE,
                border: `1px solid ${BORDER}`, borderTop: `3px solid ${kpi.color}` }}>
                <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", letterSpacing: 1.5,
                  textTransform: "uppercase", marginBottom: 6 }}>{kpi.label}</div>
                <div style={{ fontSize: 16, fontWeight: 800, color: kpi.color }}>{kpi.value}</div>
              </div>
            ))}
          </div>

          <CalloutBox title={tr("business_impact")} color={ORANGE} pageFont={pageFont}>
            {execSummaryData.businessImpact}
          </CalloutBox>

          {langCode !== "en" && regionalAdvisory && regionalAdvisory[langCode] && (
            <CalloutBox title={tr("regional_citizen_advisory")} color={BRAND} pageFont={pageFont}>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 8, color: ACCENT }}>
                {regionalAdvisory[langCode].summary}
              </div>
              <div style={{ fontSize: 11, color: RED, fontWeight: 500 }}>
                {regionalAdvisory[langCode].advisory}
              </div>
            </CalloutBox>
          )}

          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              {tr("key_findings")}
            </div>
            {[
              `Threat Family Identified: ${caseData.threatFamily || "Unclassified"}`,
              `Composite Risk Score: ${caseData.riskScore}/100 (${rm.label})`,
              `Dangerous Permissions Detected: ${highRiskPerms.length} of ${permissions.length} total`,
              `MITRE ATT&CK Techniques Mapped: ${mitreTags.length}`,
              `Network Indicators of Compromise: ${iocs.length} (${criticalIocs.length} Critical)`,
              `Blockchain Evidence: ${caseData.blockchainTxHash ? "Recorded" : "Pending"}`,
            ].map((finding, i) => (
              <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 10, padding: "8px 0",
                borderBottom: `1px solid ${BORDER}` }}>
                <span style={{ fontSize: 10, color: BRAND, fontWeight: 700, marginTop: 1 }}>▶</span>
                <span style={{ fontSize: 11, color: "#334155" }}>{finding}</span>
              </div>
            ))}
          </div>
        </>) : (
          <p style={{ color: "#64748b", fontStyle: "italic" }}>Executive summary not available.</p>
        )}
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 3: TECHNICAL MALWARE ANALYSIS                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={3} section={tr("technical_analysis")} pageFont={pageFont} />
        <SectionTitle num="2" title={tr("technical_analysis")} pageFont={pageFont} />

        {/* Primary classification card */}
        <div style={{ background: rm.bg, border: `2px solid ${rm.border}`, padding: 20, marginBottom: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <div style={{ fontSize: 9, fontWeight: 700, color: rm.color, letterSpacing: 1.5,
                textTransform: "uppercase", marginBottom: 4 }}>{tr("primary_classification")}</div>
              <div style={{ fontSize: 24, fontWeight: 900, color: rm.color, fontFamily: MONO_FONT }}>
                {caseData.threatFamily || "UNCLASSIFIED THREAT"}
              </div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 4 }}>
                {caseData.malwareType || "Android Malware"}
              </div>
            </div>
            <div style={{ textAlign: "right" }}>
              <SeverityBadge label={rm.label} pageFont={pageFont} />
              <div style={{ fontSize: 28, fontWeight: 900, color: rm.color, marginTop: 8, fontFamily: MONO_FONT }}>
                {caseData.riskScore}/100
              </div>
            </div>
          </div>
        </div>

        {/* Risk component breakdown */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 12, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            {tr("risk_score_decomp")}
          </div>
          {scoreBreakdown.map((item, i) => (
            <div key={i} style={{ marginBottom: 12 }}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
                <span style={{ fontSize: 10, fontWeight: 600, color: ACCENT }}>{item.name}</span>
                <span style={{ fontSize: 10, fontWeight: 700, color: item.color, fontFamily: MONO_FONT }}>
                  {item.score || 0}/{item.max}
                </span>
              </div>
              <ScoreBar value={Math.round(((item.score || 0) / item.max) * 100)} color={item.color} />
            </div>
          ))}
        </div>

        {/* Classification matrix table */}
        <Table
          pageFont={pageFont}
          headers={["Attribute", "Value", "Severity"]}
          rows={[
            ["Threat Family",   <code style={{ fontFamily: MONO_FONT }}>{caseData.threatFamily || "Unknown"}</code>, <SeverityBadge label={rm.label} pageFont={pageFont} />],
            ["Malware Type",    caseData.malwareType || "Android Malware", ""],
            ["Risk Score",      <code style={{ fontFamily: MONO_FONT }}>{caseData.riskScore}/100</code>, <SeverityBadge label={rm.label} pageFont={pageFont} />],
            ["AI Confidence",   <code style={{ fontFamily: MONO_FONT }}>{caseData.aiConfidence || 90}%</code>, "HIGH"],
            ["Permissions",     `${permissions.length} declared / ${highRiskPerms.length} high-risk`, highRiskPerms.length > 5 ? <SeverityBadge label="CRITICAL" pageFont={pageFont} /> : <SeverityBadge label="HIGH" pageFont={pageFont} />],
            ["IOC Count",       `${iocs.length} total / ${criticalIocs.length} critical`, criticalIocs.length > 0 ? <SeverityBadge label="CRITICAL" pageFont={pageFont} /> : ""],
            ["MITRE Techniques",`${mitreTags.length} mapped`, mitreTags.length > 5 ? <SeverityBadge label="HIGH" pageFont={pageFont} /> : <SeverityBadge label="MEDIUM" pageFont={pageFont} />],
          ]}
        />

        <CalloutBox title={tr("classification_rationale")} color={rm.color} pageFont={pageFont}>
          This sample has been classified as <strong>{rm.label}</strong> based on its composite risk
          score of <strong>{caseData.riskScore}/100</strong>. The primary risk drivers are
          {highRiskPerms.length > 0 && ` excessive permission abuse (${highRiskPerms.length} dangerous permissions),`}
          {mitreTags.length > 0 && ` mapping to ${mitreTags.length} MITRE ATT&CK techniques,`}
          {criticalIocs.length > 0 && ` and ${criticalIocs.length} critical network indicators of compromise.`}
          {" "}Immediate escalation is recommended.
        </CalloutBox>
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 4: TECHNICAL MALWARE ANALYSIS                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={4} section={tr("technical_analysis")} pageFont={pageFont} />
        <SectionTitle num="3" title={tr("technical_analysis")} pageFont={pageFont} />

        <CalloutBox title={tr("behavioral_threat_narrative")} color={BRAND} pageFont={pageFont}>
          {threatNarrative?.behavior || "Detailed behavioral analysis not available for this sample."}
        </CalloutBox>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 }}>
          {/* Static metadata */}
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              {tr("binary_metadata")}
            </div>
            {[
              { label: tr("target_binary"),    value: caseData.fileName },
              { label: tr("package_name"),     value: caseData.packageName || "N/A" },
              { label: "File Size",            value: `${((caseData.fileSize || 0) / 1024 / 1024).toFixed(2)} MB` },
              { label: tr("sha256_hash"),      value: (caseData.sha256 || "").slice(0, 32) + "..." },
            ].map((r, i) => (
              <div key={i} style={{ display: "flex", borderBottom: `1px solid ${BORDER}`,
                padding: "6px 0", fontSize: 10 }}>
                <span style={{ width: 120, fontWeight: 700, color: "#64748b", flexShrink: 0 }}>{r.label}</span>
                <span style={{ fontFamily: MONO_FONT, color: ACCENT, wordBreak: "break-all" }}>{r.value}</span>
              </div>
            ))}
          </div>

          {/* Threat vectors */}
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              {tr("threat_vector_analysis")}
            </div>
            {[
              { label: "OTP Interception",    value: threatNarrative?.otpTheft, severity: "CRITICAL" },
              { label: "Accessibility Abuse", value: threatNarrative?.accessibilityAbuse, severity: "HIGH" },
              { label: "Credential Theft",    value: threatNarrative?.credentialTheft, severity: "HIGH" },
              { label: "Fraud Risk Profile",  value: threatNarrative?.fraudRisks, severity: "MEDIUM" },
            ].map((v, i) => (
              <div key={i} style={{ padding: "8px 0", borderBottom: `1px solid ${BORDER}`, fontSize: 10 }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 2 }}>
                  <span style={{ fontWeight: 700, color: ACCENT }}>{v.label}</span>
                  <SeverityBadge label={v.severity} pageFont={pageFont} />
                </div>
                <span style={{ color: "#475569" }}>{v.value || "No indicators detected"}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Permission analysis with untranslated permission strings */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            {tr("dangerous_permissions_inventory")} ({highRiskPerms.length} of {permissions.length})
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 }}>
            {(highRiskPerms.length > 0 ? highRiskPerms : permissions).slice(0, 16).map((p, i) => (
              <div key={i} style={{ padding: "5px 10px", background: highRiskPerms.includes(p) ? "#fef2f2" : STRIPE,
                border: `1px solid ${highRiskPerms.includes(p) ? "#fca5a5" : BORDER}`,
                fontSize: 9, fontFamily: MONO_FONT,
                color: highRiskPerms.includes(p) ? RED : "#334155" }}>
                {p.replace("android.permission.", "")}
              </div>
            ))}
          </div>
        </div>
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 5: MITRE ATT&CK MAPPING                                           */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={5} section={tr("mitre_mapping")} pageFont={pageFont} />
        <SectionTitle num="4" title={tr("mitre_mapping")} pageFont={pageFont} />

        <CalloutBox title={tr("framework_reference")} color={BRAND} pageFont={pageFont}>
          The following techniques have been mapped against the MITRE ATT&CK® for Mobile framework (v14).
          Techniques are extracted through static heuristic analysis and AI behavioral correlation of
          the binary payload patterns, permission abuse, and string artefacts.
        </CalloutBox>

        {mitreTags.length > 0 ? (<>
          <Table
            pageFont={pageFont}
            headers={["Technique ID", "Technique Name", "Tactic Phase", "Confidence", "Severity"]}
            rows={mitreTags.map((tag, i) => {
              const tactic = tag.id.startsWith("T14") ? "Collection" :
                             tag.id.startsWith("T15") ? "Exfiltration" :
                             tag.id.startsWith("T16") ? "Impact" :
                             tag.id.startsWith("T10") ? "Initial Access" : "Execution";
              const conf = 90 - (i * 3);
              return [
                <span style={{ fontFamily: MONO_FONT, fontWeight: 700, color: RED, fontSize: 11 }}>{tag.id}</span>,
                <span style={{ fontWeight: 600, color: ACCENT }}>{tag.name}</span>,
                tactic,
                <span style={{ fontFamily: MONO_FONT }}>{conf}%</span>,
                <SeverityBadge label={i < 2 ? "CRITICAL" : i < 4 ? "HIGH" : "MEDIUM"} pageFont={pageFont} />,
              ];
            })}
          />
        </>) : (
          <p style={{ color: "#64748b", fontStyle: "italic" }}>No MITRE ATT&CK techniques mapped for this sample.</p>
        )}
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 6: NETWORK INFRASTRUCTURE ANALYSIS                                */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={6} section={tr("network_analysis")} pageFont={pageFont} />
        <SectionTitle num="5" title={tr("network_analysis")} pageFont={pageFont} />

        <CalloutBox title={tr("infrastructure_summary")} color={ORANGE} pageFont={pageFont}>
          Analysis has identified {iocs.length} network indicators of compromise, including {ipIocs.length} IP
          addresses and {domainIocs.length} malicious domains.
        </CalloutBox>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: 12, marginBottom: 20 }}>
          {[
            { label: tr("total_iocs"),    value: iocs.length,          color: ACCENT },
            { label: tr("critical_iocs"), value: criticalIocs.length,  color: RED    },
            { label: tr("ip_addresses"),  value: ipIocs.length,        color: ORANGE },
            { label: tr("domains"),       value: domainIocs.length,    color: BRAND  },
          ].map((kpi, i) => (
            <div key={i} style={{ padding: 14, background: STRIPE,
              border: `1px solid ${BORDER}`, borderTop: `3px solid ${kpi.color}`, textAlign: "center" }}>
              <div style={{ fontSize: 24, fontWeight: 900, color: kpi.color, fontFamily: MONO_FONT }}>{kpi.value}</div>
              <div style={{ fontSize: 9, fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: 1 }}>
                {kpi.label}
              </div>
            </div>
          ))}
        </div>

        {ipIocs.length > 0 && (<>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            {tr("c2_ip_registry")}
          </div>
          <Table
            pageFont={pageFont}
            headers={["IP Address", "Threat Role", "Severity", "Classification"]}
            rows={ipIocs.map(ioc => [
              <span style={{ fontFamily: MONO_FONT, fontWeight: 700 }}>{ioc.value}</span>,
              "Command & Control",
              <SeverityBadge label={ioc.severity?.toUpperCase() === "CRITICAL" ? "CRITICAL" : "HIGH"} pageFont={pageFont} />,
              "Bulletproof Infrastructure",
            ])}
          />
        </>)}

        {domainIocs.length > 0 && (<>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6, marginTop: 16 }}>
            {tr("malicious_domain_registry")}
          </div>
          <Table
            pageFont={pageFont}
            headers={["Domain", "Threat Role", "Severity", "Category"]}
            rows={domainIocs.map(ioc => [
              <span style={{ fontFamily: MONO_FONT, fontWeight: 700, color: RED }}>{ioc.value}</span>,
              "Phishing / C2 Relay",
              <SeverityBadge label={ioc.severity?.toUpperCase() === "CRITICAL" ? "CRITICAL" : "HIGH"} pageFont={pageFont} />,
              "Typosquatting / Fraud Gateway",
            ])}
          />
        </>)}

        <CalloutBox title={tr("banking_impact_vector")} color={RED} pageFont={pageFont}>
          {threatNarrative?.bankingImpact || "Network infrastructure assessment indicates potential for financial fraud facilitation."}
        </CalloutBox>
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 7: INDICATORS OF COMPROMISE                                       */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={7} section={tr("iocs_title")} pageFont={pageFont} />
        <SectionTitle num="6" title={tr("iocs_title")} pageFont={pageFont} />

        <CalloutBox title={tr("ioc_methodology")} color={BRAND} pageFont={pageFont}>
          IOCs were extracted through static string analysis, permission profiling, and AI-assisted
          behavioral pattern matching.
        </CalloutBox>

        {iocs.length > 0 ? (
          <Table
            pageFont={pageFont}
            pageBreakInside="auto"
            headers={["#", "IOC Type", "Indicator Value", "Severity", "Action Required"]}
            rows={iocs.map((ioc, i) => [
              <span style={{ color: "#94a3b8", fontSize: 9, fontFamily: MONO_FONT }}>{i + 1}</span>,
              <span style={{ fontWeight: 700, color: BRAND, textTransform: "uppercase", fontSize: 9, fontFamily: MONO_FONT }}>{ioc.type}</span>,
              <span style={{ fontFamily: MONO_FONT, fontSize: 9, color: ioc.severity?.toLowerCase() === "critical" ? RED : ACCENT, wordBreak: "break-all" }}>{ioc.value}</span>,
              <SeverityBadge label={ioc.severity?.toUpperCase() === "CRITICAL" ? "CRITICAL" : ioc.severity?.toUpperCase() === "HIGH" ? "HIGH" : "MEDIUM"} pageFont={pageFont} />,
              ioc.severity?.toLowerCase() === "critical" ? tr("immediate_block") : tr("monitor_alert"),
            ])}
          />
        ) : (
          <p style={{ color: "#64748b", fontStyle: "italic" }}>No network indicators of compromise identified.</p>
        )}

        {/* Hash IOC section */}
        <div style={{ marginTop: 16 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            {tr("binary_hash_fingerprints")}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "120px 1fr", gap: 0, fontSize: 10 }}>
            {[
              { label: "SHA-256", value: caseData.sha256 },
            ].map((h, i) => (
              <React.Fragment key={i}>
                <div style={{ padding: "8px 12px", background: ACCENT, color: "#fff",
                  fontWeight: 700, fontSize: 9, letterSpacing: 1, display: "flex", alignItems: "center" }}>
                  {h.label}
                </div>
                <div style={{ padding: "8px 12px", background: STRIPE, border: `1px solid ${BORDER}`,
                  fontFamily: MONO_FONT, fontSize: 9, wordBreak: "break-all" }}>
                  {h.value || "N/A"}
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 8: CITIZEN IMPACT ASSESSMENT                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={8} section={tr("citizen_impact")} pageFont={pageFont} />
        <SectionTitle num="7" title={tr("citizen_impact")} pageFont={pageFont} />

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, marginBottom: 20 }}>
          {[
            { label: tr("affected_population"), value: citizenImpact?.affectedPopulation || "High Exposure", color: RED },
            { label: tr("target_group"),        value: citizenImpact?.targetGroup || "UPI & Mobile Banking Users", color: ORANGE },
            { label: tr("priority_level"),      value: citizenImpact?.priority || "Immediate Action", color: rm.color },
          ].map((kpi, i) => (
            <div key={i} style={{ padding: 16, background: STRIPE,
              border: `1px solid ${BORDER}`, borderTop: `3px solid ${kpi.color}` }}>
              <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", letterSpacing: 1.5,
                textTransform: "uppercase", marginBottom: 6 }}>{kpi.label}</div>
              <div style={{ fontSize: 13, fontWeight: 800, color: kpi.color }}>{kpi.value}</div>
            </div>
          ))}
        </div>

        <Table
          pageFont={pageFont}
          headers={["Impact Dimension", "Assessment", "Severity"]}
          rows={[
            ["Fraud Type",           citizenImpact?.fraudType || "UPI/IMPS Financial Fraud",   <SeverityBadge label="CRITICAL" pageFont={pageFont} />],
            ["Affected Segment",     citizenImpact?.targetGroup || "Retail Banking Customers",  <SeverityBadge label="HIGH" pageFont={pageFont} />],
            ["OTP Theft Risk",       threatNarrative?.otpTheft || "Active indicators detected", <SeverityBadge label="CRITICAL" pageFont={pageFont} />],
            ["Data Exfiltration",    threatNarrative?.credentialTheft || "Credential harvesting confirmed", <SeverityBadge label="HIGH" pageFont={pageFont} />],
            ["Accessibility Abuse",  threatNarrative?.accessibilityAbuse || "Overlay attack possible",  <SeverityBadge label="HIGH" pageFont={pageFont} />],
          ]}
        />

        <CalloutBox title={tr("rbi_advisory_context")} color={RED} pageFont={pageFont}>
          Based on the observed threat behavior, this application poses significant risk to Indian
          mobile banking users. The combination of SMS interception, accessibility service abuse,
          and credential harvesting capabilities aligns with patterns associated with UPI fraud campaigns.
        </CalloutBox>
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 9: BANK OFFICER MITIGATION PLAN                                  */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont}>
        <PageHeader pageNum={9} section={tr("bank_mitigation")} pageFont={pageFont} />
        <SectionTitle num="8" title={tr("bank_mitigation")} pageFont={pageFont} />

        <CalloutBox title={tr("compliance_context")} color={BRAND} pageFont={pageFont}>
          This section provides actionable guidance for bank compliance officers, fraud prevention
          teams, and IT security departments. Recommendations are aligned with RBI Cybersecurity Framework.
        </CalloutBox>

        <Table
          pageFont={pageFont}
          headers={["Priority", "Action Item", "Owner", "Timeline", "Status"]}
          rows={[
            [<SeverityBadge label="CRITICAL" pageFont={pageFont} />, "Block identified C2 IPs at perimeter firewall", "Network Security Team", "Immediate (0-2 hrs)", "Required"],
            [<SeverityBadge label="CRITICAL" pageFont={pageFont} />, "Add malicious domains to DNS blocklist", "IT Security", "Immediate (0-4 hrs)", "Required"],
            [<SeverityBadge label="HIGH" pageFont={pageFont} />, "Alert fraud monitoring system with IOC signatures", "Fraud Analytics", "Same Day", "Required"],
            [<SeverityBadge label="HIGH" pageFont={pageFont} />, "Issue customer advisory for suspicious app", "Digital Banking", "24 Hours", "Urgent"],
            [<SeverityBadge label="HIGH" pageFont={pageFont} />, "Escalate to CERT-In via cybersecurity reporting portal", "CISO Office", "24 Hours", "Urgent"],
          ]}
        />
        <PageFooter caseId={cid} pageFont={pageFont} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 10: EVIDENCE INTEGRITY                                            */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageFont={pageFont} pageBreakAfter={false}>
        <PageHeader pageNum={10} section={tr("evidence_integrity")} pageFont={pageFont} />
        <SectionTitle num="9" title={tr("evidence_integrity")} pageFont={pageFont} />

        <CalloutBox title={tr("chain_of_custody_statement")} color={GREEN} pageFont={pageFont}>
          All digital evidence in this investigation has been cryptographically hashed and recorded
          on an immutable blockchain ledger, guaranteeing tamper-proof integrity of findings.
        </CalloutBox>

        {/* Blockchain details with untranslated hashes in mono */}
        <div style={{ background: "#f0fdf4", border: `2px solid #86efac`, padding: 20, marginBottom: 20 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke={GREEN} strokeWidth="2">
              <path d="M12 2L3 7v5c0 5 3.5 9.74 9 11 5.5-1.26 9-6 9-11V7L12 2z" />
              <path d="M9 12l2 2 4-4" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            <span style={{ fontWeight: 800, color: GREEN, fontSize: 13, textTransform: "uppercase", letterSpacing: 1.5 }}>
              {tr("blockchain_record")}
            </span>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "180px 1fr", gap: 0, fontSize: 10 }}>
            {[
              { label: "Network",             value: "Sepolia Testnet (Ethereum-compatible)", mono: false },
              { label: "Transaction Hash",    value: caseData.blockchainTxHash || "Pending — awaiting confirmation", mono: true },
              { label: "Block Number",        value: caseData.blockchainBlock ? `#${caseData.blockchainBlock}` : "N/A", mono: true },
              { label: "Ledger Timestamp",    value: fmt(caseData.blockchainTimestamp), mono: false },
              { label: "Evidence Type",       value: "SHA-256 Digest of Analysis Report", mono: false },
              { label: "Integrity Status",    value: caseData.blockchainTxHash ? "✓ VERIFIED — Tamper-proof record exists" : "⏳ PENDING — Awaiting on-chain confirmation", mono: false },
            ].map((row, i) => (
              <React.Fragment key={i}>
                <div style={{ padding: "8px 12px", background: "rgba(22,101,52,0.1)",
                  fontWeight: 700, fontSize: 9, letterSpacing: 1, color: GREEN,
                  textTransform: "uppercase", borderBottom: `1px solid #bbf7d0`,
                  display: "flex", alignItems: "center" }}>
                  {row.label}
                </div>
                <div style={{ padding: "8px 12px", borderBottom: `1px solid #bbf7d0`,
                  fontFamily: row.mono ? MONO_FONT : pageFont,
                  fontSize: 9, color: ACCENT, wordBreak: "break-all",
                  background: i % 2 === 0 ? "#fff" : "#f0fdf4" }}>
                  {row.value}
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>

        <CalloutBox title={tr("digital_admissibility")} color={GREEN} pageFont={pageFont}>
          All exhibits are hashed, timestamped, and blockchain-anchored under Case <code style={{ fontFamily: MONO_FONT }}>{cid}</code>. Chain of custody
          maintained per CERT-In guidelines and IT Act 2000 Section 65B digital evidence standards.
        </CalloutBox>

        {/* Final branding bar */}
        <div style={{ marginTop: "auto", background: ACCENT, color: "#fff",
          padding: "12px 24px", margin: "auto -48px -36px",
          display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2 }}>BeaconTrap Intelligence Platform</span>
          <span style={{ fontSize: 9, color: "#94a3b8", fontFamily: MONO_FONT }}>
            © {new Date().getFullYear()} · Case {cid} · Classification: CONFIDENTIAL
          </span>
        </div>
      </Page>

    </div>
  );
}
